[twitch] 
login_name = 'your_bot_name'
channel_name = 'stuck_overflow'
client_id = 'YOURCLIENTID'
secret = 'YOURSECRET'
token_filepath = '.twitchauthtoken.json'

[queue_manager]
capacity = 10
queue_storage = 'queue_storage.json'

[giphy]
api_key = 'YOUR_GIPHY_API_KEY'

#Configuration settings for obs related features
[obs]
host = 'localhost'
port = 4444
password = 'STUCKER'

# This should be of type browser source
gif_source = 'GifBot'

